import { useState } from 'react';
import { Button, Input } from '@cloudflare/kumo';
import type { AssertionMode, PatchOperation, Snapshot, StatementRole } from '../../types/api';
import * as api from '../../lib/research/api';
import { allObligations } from '../../lib/research/graph';
import { panel, panelSection } from '../ui/classes';
import { FileTextIcon, ArrowRightIcon } from '@phosphor-icons/react';
import { ExtractionProgress } from './ResearchUpload';
export type Perform = (action: () => Promise<void>) => Promise<void>;
export function MaterialPanel({ state, busy, perform, refresh, onSelect, onArgument }: { state: Snapshot; busy: boolean; perform: Perform; refresh: () => Promise<void>; onSelect: (id: string) => void; onArgument: () => void }) {
  const [sourceId, setSourceId] = useState(''); const [jobId, setJobId] = useState('');
  const [text, setText] = useState(''); const [mode, setMode] = useState<AssertionMode>('asserted'); const [role, setRole] = useState<StatementRole>('premise'); const [excerptIds, setExcerptIds] = useState<string[]>([]);
  const [conclusion, setConclusion] = useState(''); const [premises, setPremises] = useState<string[]>([]); const [explanation, setExplanation] = useState(''); const [patchText, setPatchText] = useState('');
  const [relationSource, setRelationSource] = useState(''); const [relationTarget, setRelationTarget] = useState(''); const [relationKind, setRelationKind] = useState<'supports' | 'rebuts' | 'undercuts' | 'qualifies' | 'specializes' | 'revises'>('supports'); const [relationReason, setRelationReason] = useState('');
  const objects = [...state.graph.statements.map(s => ({ id: s.id, label: s.text, kind: 'statement' as const })), ...state.graph.reasoning_steps.map(s => ({ id: s.id, label: s.explanation, kind: 'reasoning_step' as const }))];
  const id = state.workspace.id;
  async function patch(operations: PatchOperation[]) { await api.patchGraph(id, operations); await refresh(); }
  return <div className={panel}><div className="mx-auto max-w-5xl">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-medium tracking-tight">Your research</h1><p className="mt-2 text-sm text-zinc-500">Papers and passages that support the argument.</p></div>{!!state.graph.statements.length && <Button size="sm" variant="outline" icon={<ArrowRightIcon size={15}/>} onClick={onArgument}>View argument</Button>}</div>
    <p className="max-w-2xl text-sm leading-[1.9] text-zinc-500">The documents behind your argument are collected here. Attach another paper or paste notes in the bar below to add research, then open a source to inspect the passages used as evidence.</p>
    {!!state.sources.length && <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-medium">Added material</h2><span className="text-xs text-zinc-500">{state.sources.length} {state.sources.length === 1 ? 'document' : 'documents'}</span></div>
      <div className="space-y-3">{state.sources.map(source => {
        const jobs = state.jobs.filter(job => job.source_id === source.id);
        const active = jobs.find(job => !['succeeded', 'failed', 'cancelled'].includes(job.status));
        const latest = active ?? [...jobs].sort((a, b) => b.created_at.localeCompare(a.created_at))[0];
        const failed = latest && ['failed', 'cancelled'].includes(latest.status);
        const hasArgument = latest?.status === 'succeeded' || state.graph.statements.some(statement => statement.excerpt_ids.some(excerptId => source.excerpts.some(excerpt => excerpt.id === excerptId)));
        const status = active ? 'Building argument…' : failed ? 'Extraction stopped' : hasArgument ? 'Argument ready' : 'Ready to build';
        return <div key={source.id} className="rounded-sm border border-line bg-white p-4">
          <div className="flex flex-wrap items-center gap-3"><FileTextIcon size={20} className="shrink-0 text-zinc-400"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium" title={source.original_filename}>{source.original_filename}</p><p role={active ? 'status' : undefined} className="mt-1 text-xs text-zinc-500">{status}{active && latest.total_chunks > 0 ? ` · ${Math.round(latest.completed_chunks / latest.total_chunks * 100)}%` : ''}</p></div>
            {active ? <Button size="xs" variant="ghost" disabled={busy} onClick={() => perform(async () => { await api.cancelJob(active.id); await refresh(); })}>Cancel</Button> : !failed && hasArgument && state.graph.statements.length ? <Button size="sm" variant="outline" onClick={onArgument}>View argument</Button> : <Button size="sm" variant="outline" loading={busy} onClick={() => perform(async () => { await api.extract(source); await refresh(); })}>{failed ? 'Retry extraction' : 'Build argument'}</Button>}
          </div>
          {active && <ExtractionProgress completed={active.completed_chunks} total={active.total_chunks} queued={active.status === 'queued'}/>}
          {failed && latest.error && <p role="alert" className="mt-3 text-xs text-fail">{latest.error}</p>}
          <details className="mt-3 text-xs"><summary className="cursor-pointer text-zinc-500">View source excerpts ({source.excerpts.length})</summary><Button size="xs" variant="ghost" className="mt-3" onClick={() => onSelect(source.id)}>Inspect source</Button>{source.excerpts.map(excerpt => <Button key={excerpt.id} size="sm" variant="ghost" className="mt-2 h-auto! w-full justify-start! text-left text-xs! whitespace-normal!" onClick={() => onSelect(excerpt.id)}>{excerpt.text}</Button>)}</details>
        </div>;
      })}</div>
    </section>}
    <details className="mt-7 border-t border-line pt-5"><summary className="cursor-pointer text-xs text-zinc-500">Advanced tools</summary><p className="mt-3 text-xs text-zinc-500">Edit claims and reasoning manually, or reconnect existing material.</p>
      <details className="mt-4"><summary className="cursor-pointer text-[11px]">Reconnect a source or extraction job</summary><p className="my-3 text-[10px] text-zinc-500">Source and job IDs are remembered in this browser. Use an ID from another session or an exported snapshot to reconnect existing material.</p><div className="flex gap-2"><Input size="sm" aria-label="Existing source ID" placeholder="Source UUID" value={sourceId} onChange={e => setSourceId(e.target.value)}/><Button size="sm" disabled={busy || !sourceId.trim()} onClick={() => perform(async () => { await api.attachSource(id, sourceId.trim()); setSourceId(''); await refresh(); })}>Attach source</Button></div><div className="mt-3 flex gap-2"><Input size="sm" aria-label="Existing job ID" placeholder="Job UUID" value={jobId} onChange={e => setJobId(e.target.value)}/><Button size="sm" disabled={busy || !jobId.trim()} onClick={() => perform(async () => { const job = await api.attachJob(id, jobId.trim()); await api.attachSource(id, job.source_id); setJobId(''); await refresh(); })}>Attach job</Button></div></details>
    <details className={panelSection}><summary className="cursor-pointer text-xs font-medium">Propose a statement</summary><div className="h-3"/><div className="grid gap-3"><Input size="sm" label="Statement text" value={text} onChange={e => setText(e.target.value)}/><div className="flex flex-wrap gap-4"><label>Assertion <select aria-label="Assertion mode" className="rounded border border-line p-2" value={mode} onChange={e => setMode(e.target.value as AssertionMode)}>{['asserted', 'hypothesis', 'conditional', 'question', 'reported'].map(m => <option key={m}>{m}</option>)}</select></label><label>Role <select aria-label="Statement role" className="rounded border border-line p-2" value={role} onChange={e => setRole(e.target.value as StatementRole)}>{['premise', 'conclusion', 'assumption', 'objection', 'definition'].map(m => <option key={m}>{m}</option>)}</select></label></div><p className="text-[10px] text-zinc-500">Select the excerpts that ground this statement.</p>{state.sources.flatMap(s => s.excerpts).map(e => <label key={e.id} className="flex items-start gap-2 text-[11px]"><input type="checkbox" checked={excerptIds.includes(e.id)} onChange={ev => setExcerptIds(ev.target.checked ? [...excerptIds, e.id] : excerptIds.filter(x => x !== e.id))}/>{e.text}</label>)}<Button size="sm" disabled={busy || !text.trim()} className="justify-self-start" onClick={() => perform(async () => { await patch([{ op: 'create_statement', client_ref: 'statement', text: text.trim(), assertion_mode: mode, role, excerpt_ids: excerptIds, provenance: api.userProvenance }]); setText(''); setExcerptIds([]); })}>Propose statement</Button></div></details>
    <details className={panelSection}><summary className="cursor-pointer text-xs font-medium">Declare a reasoning step</summary><div className="h-3"/><p className="mb-3 text-[10px] text-zinc-500">All selected premises are required together. Separate steps represent alternative support paths.</p><label>Conclusion<select aria-label="Reasoning conclusion" className="mt-1 w-full rounded border border-line p-2" value={conclusion} onChange={e => { setConclusion(e.target.value); setPremises(p => p.filter(x => x !== e.target.value)); }}><option value="">Choose a conclusion</option>{state.graph.statements.map(s => <option key={s.id} value={s.id}>{s.text}</option>)}</select></label><div className="my-3 grid gap-2">{state.graph.statements.filter(s => s.id !== conclusion).map(s => <label key={s.id} className="flex items-start gap-2 text-[11px]"><input type="checkbox" checked={premises.includes(s.id)} onChange={e => setPremises(e.target.checked ? [...premises, s.id] : premises.filter(p => p !== s.id))}/>{s.text}</label>)}</div><Input size="sm" label="Reasoning explanation" value={explanation} onChange={e => setExplanation(e.target.value)}/><Button size="sm" className="mt-3" disabled={busy || !conclusion || !premises.length || !explanation.trim()} onClick={() => perform(async () => { await patch([{ op: 'create_reasoning_step', client_ref: 'reasoning', premise_ids: premises, conclusion_id: conclusion, explanation: explanation.trim(), provenance: api.userProvenance }]); setExplanation(''); setPremises([]); setConclusion(''); })}>Propose reasoning step</Button></details>
    <details className={panelSection}><summary className="cursor-pointer text-xs font-medium">Propose a relation</summary><div className="h-3"/><p className="mb-3 text-[10px] text-zinc-500">Link argument objects with an explicit rationale. Relations remain inspectable proposals.</p><div className="grid gap-3"><label>From<select aria-label="Relation source" className="mt-1 w-full rounded border border-line p-2" value={relationSource} onChange={e => setRelationSource(e.target.value)}><option value="">Choose an argument object</option>{objects.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>Relation<select aria-label="Relation kind" className="ml-3 rounded border border-line p-2" value={relationKind} onChange={e => setRelationKind(e.target.value as typeof relationKind)}>{['supports', 'rebuts', 'undercuts', 'qualifies', 'specializes', 'revises'].map(r => <option key={r}>{r}</option>)}</select></label><label>To<select aria-label="Relation target" className="mt-1 w-full rounded border border-line p-2" value={relationTarget} onChange={e => setRelationTarget(e.target.value)}><option value="">Choose an argument object</option>{objects.filter(o => o.id !== relationSource).map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label><Input size="sm" label="Relation rationale" value={relationReason} onChange={e => setRelationReason(e.target.value)}/><Button size="sm" className="justify-self-start" disabled={busy || !relationSource || !relationTarget || relationSource === relationTarget || !relationReason.trim()} onClick={() => perform(async () => { const from = objects.find(o => o.id === relationSource)!; const to = objects.find(o => o.id === relationTarget)!; await patch([{ op: 'create_relation', source_node_kind: from.kind, source_node_id: from.id, target_node_kind: to.kind, target_node_id: to.id, relation: relationKind, metadata: { lifecycle: 'proposed', rationale: relationReason.trim(), provenance: api.userProvenance } }]); setRelationReason(''); setRelationSource(''); setRelationTarget(''); })}>Propose relation</Button></div></details>
    <details className={panelSection}><summary className="cursor-pointer text-xs font-medium">Review candidates</summary><div className="h-3"/>{state.graph.statements.map(s => <Button variant="ghost" size="sm" key={s.id} className="h-auto! w-full justify-between! border-b border-line py-3! text-left text-[11px]! whitespace-normal!" onClick={() => onSelect(s.id)}><span>{s.text}</span><span className="ml-4 shrink-0 text-[10px] text-zinc-500">{s.lifecycle}</span></Button>)}</details>
    <details className={panelSection}><summary className="cursor-pointer text-[11px]">Advanced graph patch</summary><p className="my-2 text-[10px] text-zinc-500">Backend operations: create_statement, create_reasoning_step, create_relation, create_annotation. Every statement and reasoning step remains proposed until reviewed. References and workspace boundaries are validated by the API.</p><textarea aria-label="Graph patch operations" className="min-h-40 w-full rounded border border-line p-3 font-mono text-[11px]" value={patchText} onChange={e => setPatchText(e.target.value)}/><Button size="sm" className="mt-2" disabled={busy || !patchText.trim()} onClick={() => perform(async () => { const ops: unknown = JSON.parse(patchText); if (!Array.isArray(ops) || !ops.length) throw new Error('Enter a non-empty JSON operations array.'); await patch(ops as PatchOperation[]); setPatchText(''); })}>Submit graph patch</Button></details>
    </details>
  </div></div>;
}
export function ArgumentChain({ state, target, onSelect }: { state: Snapshot; target?: string; onSelect: (id: string) => void }) {
  function render(id: string, path = new Set<string>(), depth = 0): React.ReactNode {
    if (path.has(id) || depth > 20) return <p className="text-warn">Dependency limit reached.</p>;
    const next = new Set([...path, id]); const steps = state.graph.reasoning_steps.filter(r => r.conclusion_id === id);
    return <div key={id} className="mt-3 border-l border-line pl-4"><Button variant="ghost" size="sm" className="h-auto! justify-start! px-0! text-left whitespace-normal!" onClick={() => onSelect(id)}>{state.graph.statements.find(s => s.id === id)?.text}</Button>{allObligations(state).filter(o => o.status === 'open' && o.blocks_statement_id === id).map(o => <Button key={o.id} variant="ghost" size="xs" className="mt-2 h-auto! text-left text-fail! whitespace-normal!" onClick={() => onSelect(o.id)}>{o.description}</Button>)}{steps.map(r => <div key={r.id} className="my-3 rounded border border-line p-3"><Button variant="ghost" size="xs" className="h-auto! text-left whitespace-normal!" onClick={() => onSelect(r.id)}>{r.explanation} · {r.lifecycle}</Button><p className="mt-2 text-[10px] text-zinc-500">All premises below are required together{steps.length > 1 ? ' · alternative support step' : ''}</p>{r.premise_ids.map(p => render(p, next, depth + 1))}</div>)}</div>;
  }
  return <div className={panel}><h1 className="text-lg">Argument chain</h1><p className="mt-2 text-[11px] text-zinc-500">Reasoning steps retain their premise groups. Inspect every dependency before accepting a conclusion.</p>{target ? render(target) : <p className="mt-6 text-zinc-500">Choose a statement on the argument canvas.</p>}</div>;
}
