'use client';
import { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Input, Tabs, cn } from '@cloudflare/kumo';
import { ArrowClockwiseIcon, PlusIcon, SidebarSimpleIcon, TrashIcon } from '@phosphor-icons/react';
import * as api from '../../lib/research/api';
import { loadDemo } from '../../lib/research/demo';
import { allObligations, filterGraph, humanize, projectWorkspace } from '../../lib/research/graph';
import type { Snapshot, Verification } from '../../types/api';
import { ResearchCanvas } from './ResearchCanvas';
import { ResearchInspector } from './ResearchInspector';
import { ArgumentChain, MaterialPanel } from './ResearchPanels';
import { panel, panelSection } from '../ui/classes';
const row = 'h-auto! min-h-8 w-full justify-start! px-2! py-2! text-left text-[11px]! font-normal! whitespace-normal!';
export function ResearchWorkspace() {
  const client = useQueryClient();
  const [id, setId] = useState<string>(); const [selected, setSelected] = useState<string>(); const [target, setTarget] = useState<string>(); const [tab, setTab] = useState('argument');
  const [collapsed, setCollapsed] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [title, setTitle] = useState(''); const [deleting, setDeleting] = useState(false);
  const [query, setQuery] = useState(''); const [lifecycle, setLifecycle] = useState(''); const [source, setSource] = useState(''); const [verification, setVerification] = useState<Record<string, Verification>>({});
  const workspaces = useQuery({ queryKey: ['workspaces'], queryFn: api.listWorkspaces, refetchInterval: 10000, retry: 1 });
  const current = useQuery({ queryKey: ['snapshot', id], queryFn: () => api.fetchSnapshot(id!), enabled: !!id, refetchInterval: 3000, retry: 1 });
  const health = useQuery({ queryKey: ['health'], queryFn: api.health, refetchInterval: 15000, retry: false });
  const state = current.data;
  const graph = useMemo(() => state ? filterGraph(projectWorkspace(state), query, lifecycle, source) : { nodes: [], edges: [] }, [state, query, lifecycle, source]);
  useEffect(() => {
    function sync() { const saved = new URLSearchParams(window.location.search).get('workspace'); setId(saved || undefined); setSelected(undefined); setTarget(undefined); }
    sync(); window.addEventListener('popstate', sync); return () => window.removeEventListener('popstate', sync);
  }, []);
  function load(workspace?: string, material = false) {
    setId(workspace); setSelected(undefined); setTarget(undefined); setTab(material ? 'material' : 'argument'); setError(''); setNotice(''); setQuery(''); setLifecycle(''); setSource(''); setDeleting(false);
    const url = new URL(window.location.href); if (workspace) url.searchParams.set('workspace', workspace); else url.searchParams.delete('workspace'); window.history.pushState(null, '', url);
  }
  async function refresh() { await Promise.all([client.invalidateQueries({ queryKey: ['snapshot'] }), client.invalidateQueries({ queryKey: ['workspaces'] }), client.invalidateQueries({ queryKey: ['health'] })]); }
  async function perform(action: () => Promise<void>) {
    setBusy(true); setError(''); setNotice('');
    try { await action(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { await refresh(); setBusy(false); }
  }
  function show(node: string) { setSelected(node); if (state?.graph.statements.some(s => s.id === node)) setTarget(node); setTab('argument'); }
  async function runVerification(workspace: string) {
    const result = await api.verify(workspace); setVerification(v => ({ ...v, [workspace]: result })); await refresh();
    setNotice(`Verification completed: ${result.issues_opened} issues opened, ${result.issues_resolved} resolved; ${result.obligations_opened} obligations opened, ${result.obligations_resolved} resolved.`);
  }
  const lastVerification = id ? verification[id] : undefined;
  const knownObligations = state ? allObligations(state).filter(o => o.status === 'open').length : 0;
  const targets = state?.graph.statements.filter(s => s.role === 'conclusion') ?? [];
  const activeJobs = state?.jobs.filter(j => !['succeeded', 'failed', 'cancelled'].includes(j.status)) ?? [];
  return <main className="flex h-dvh min-h-[560px] overflow-hidden text-xs"><aside aria-label="Research navigation" className={cn('flex shrink-0 flex-col border-r border-line bg-zinc-100 p-2', collapsed ? 'w-[58px]' : 'w-[208px] max-[700px]:w-[58px]')}>
    <div className="flex h-11 items-center justify-between px-1"><button className={cn('text-[13px] font-semibold', collapsed && 'hidden', 'max-[700px]:hidden')} onClick={() => load()}>Trial</button><Button size="sm" variant="ghost" shape="square" aria-label="Toggle research navigation" icon={<SidebarSimpleIcon size={17}/>} onClick={() => setCollapsed(!collapsed)}/></div>
    <Button size="sm" variant="outline" disabled={busy} className="my-3 text-[11px]!" icon={<PlusIcon size={14}/>} aria-label="New research workspace" onClick={() => load()}><span className={cn(collapsed && 'hidden', 'max-[700px]:hidden')}>New research</span></Button>
    {!collapsed && <div className="flex-1 overflow-y-auto max-[700px]:hidden"><p className="px-2 py-2 text-[10px] text-zinc-500">Research workspaces</p>{workspaces.data?.map(w => <Button variant="ghost" size="sm" disabled={busy} key={w.id} className={cn(row, id === w.id && 'bg-zinc-200!')} onClick={() => load(w.id)}><span className="line-clamp-2">{w.title}</span></Button>)}{!!targets.length && <><p className="mt-4 px-2 py-2 text-[10px] text-zinc-500">Target conclusions</p>{targets.map(s => <Button size="sm" variant="ghost" key={s.id} className={cn(row, target === s.id && 'bg-zinc-200!')} onClick={() => { setTarget(s.id); show(s.id); }}>{s.text}</Button>)}</>}</div>}
    <div className="mt-auto border-t border-line pt-3"><p className="px-2 text-[10px] text-zinc-500">{health.data?.status === 'ok' ? 'API connected' : health.isPending ? 'Connecting…' : 'API unavailable'}</p><a href="/docs" target="_blank" rel="noreferrer" className={cn('mt-3 block px-2 text-[10px] text-zinc-500 underline', collapsed && 'hidden', 'max-[700px]:hidden')}>API documentation</a></div>
  </aside><section className="flex min-w-0 flex-1 flex-col"><header className="flex min-h-[52px] shrink-0 items-center justify-between gap-3 border-b border-line bg-zinc-50 px-5"><div className="flex min-w-0 items-center gap-3 text-[11px]"><span className="text-zinc-500 max-[700px]:hidden">Research</span><span className="text-zinc-300 max-[700px]:hidden">/</span><strong className="truncate font-medium">{state?.workspace.title ?? 'New argument graph'}</strong></div><div className="flex shrink-0 items-center gap-2">{id && <select aria-label="Switch workspace" className="max-w-36 rounded border border-line bg-transparent p-1 text-[10px] min-[701px]:hidden" value={id} onChange={e => load(e.target.value)}>{workspaces.data?.map(w => <option key={w.id} value={w.id}>{w.title}</option>)}</select>}{state && <><Button size="xs" variant="ghost" disabled={busy} onClick={() => api.downloadSnapshot(state)}>Export</Button><Button size="xs" variant="ghost" shape="square" disabled={busy} aria-label="Refresh workspace" icon={<ArrowClockwiseIcon size={14}/>} onClick={() => perform(refresh)}/><Button size="xs" variant="ghost" shape="square" disabled={busy} aria-label="Delete workspace" icon={<TrashIcon size={14}/>} onClick={() => setDeleting(true)}/></>}</div></header>
    {id && <div className="flex min-h-[43px] shrink-0 flex-wrap items-center justify-between gap-2 border-b border-line bg-zinc-50 px-4 py-1 [&_[role=tab]]:text-[11px]"><Tabs size="sm" variant="underline" value={tab} onValueChange={value => { setTab(value); setSelected(undefined); }} tabs={[{ value: 'argument', label: 'Argument' }, { value: 'material', label: 'Material' }, { value: 'chain', label: 'Chain' }, { value: 'checks', label: 'Checks' }]}/><span className="text-[10px] text-zinc-500 max-[1000px]:hidden">{knownObligations} visible statement obligations{activeJobs.length ? ` · ${activeJobs.length} extraction jobs` : ''}</span></div>}
    {deleting && state && <div className="flex flex-wrap items-center justify-between gap-3 border-b border-red-200 bg-red-50 px-5 py-3 text-[11px]"><p>Delete “{state.workspace.title}” and all of its graph data? This cannot be undone.</p><div className="flex gap-2"><Button size="xs" disabled={busy} variant="ghost" onClick={() => setDeleting(false)}>Keep workspace</Button><Button size="xs" disabled={busy} variant="destructive" onClick={() => perform(async () => { await api.deleteWorkspace(state.workspace.id); client.removeQueries({ queryKey: ['snapshot', state.workspace.id] }); load(); })}>Delete permanently</Button></div></div>}
    <div className="relative min-h-0 flex-1 overflow-hidden">
      {!id ? <div className="mx-auto flex h-full max-w-4xl flex-col justify-center gap-5 overflow-y-auto px-12 max-[700px]:px-6"><p className="text-[10px] text-zinc-500">Inspect the reasoning</p><h1 className="text-[42px] leading-tight tracking-[-.045em] max-[700px]:text-[32px]">What does this<br/>conclusion depend on?</h1><p className="max-w-lg text-[13px] leading-relaxed text-zinc-500">Build an auditable argument from papers and notes. See exact source excerpts, review proposed reasoning, and find what remains to be established.</p><form className="mt-3 flex max-w-lg gap-3 max-[500px]:flex-col" onSubmit={e => { e.preventDefault(); void perform(async () => { const workspace = await api.createWorkspace(title.trim() || 'Untitled research'); load(workspace.id, true); setTitle(''); }); }}><Input className="min-w-0 flex-1" aria-label="Workspace title" maxLength={255} size="sm" placeholder="Research workspace title" value={title} onChange={e => setTitle(e.target.value)}/><Button type="submit" size="sm" loading={busy}>Create workspace</Button></form><div className="mt-3"><Button size="sm" variant="outline" loading={busy} onClick={() => perform(async () => { const result = await loadDemo(workspace => load(workspace)); setVerification(v => ({ ...v, [result.workspace.id]: result.verification })); setNotice('Synthetic demo loaded through the live backend. Inspect the unsupported human conclusion and its proof obligations.'); })}>Try the synthetic study demo</Button></div><p className="max-w-lg text-[10px] leading-relaxed text-zinc-400">The demo uses clearly labelled synthetic material and the real verifier. It works without model credentials. Claude extraction, critique and synthesis use the backend’s configured provider.</p>{!!workspaces.data?.length && <select aria-label="Open existing workspace" className="max-w-lg rounded border border-line p-2 min-[701px]:hidden" defaultValue="" onChange={e => load(e.target.value)}><option value="" disabled>Open an existing workspace</option>{workspaces.data.map(w => <option key={w.id} value={w.id}>{w.title}</option>)}</select>}</div>
      : !state ? <div className="p-8 text-zinc-500"><p>{current.error?.message ?? 'Loading graph…'}</p><Button className="mt-3" size="sm" variant="outline" disabled={busy} onClick={() => perform(refresh)}>Retry connection</Button><Button className="ml-3 mt-3" size="sm" variant="ghost" onClick={() => load()}>Back to workspaces</Button></div>
      : <>{tab === 'argument' ? <><ResearchCanvas key={id} graph={graph} selected={selected} onSelect={node => { setSelected(node); if (state.graph.statements.some(s => s.id === node)) setTarget(node); }}/><div className={cn('absolute top-4 left-4 z-5 flex max-w-[calc(100%-32px)] flex-wrap items-center gap-2 rounded-md border border-line bg-white/95 p-2', selected && 'min-[900px]:max-w-[calc(100%-380px)]')}><Input size="xs" aria-label="Search graph" placeholder="Search statements or identifiers" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Graph lifecycle filter" className="rounded border border-line p-1 text-[10px]" value={lifecycle} onChange={e => setLifecycle(e.target.value)}><option value="">All review states</option><option value="proposed">Proposed</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select><select aria-label="Graph source filter" className="max-w-32 rounded border border-line p-1 text-[10px]" value={source} onChange={e => setSource(e.target.value)}><option value="">All sources</option>{state.sources.map(s => <option key={s.id} value={s.id}>{s.original_filename}</option>)}</select>{(query || lifecycle || source) && <Button size="xs" variant="ghost" onClick={() => { setQuery(''); setLifecycle(''); setSource(''); }}>Reset filters</Button>}</div>{!graph.nodes.length && <div className="pointer-events-none absolute inset-0 flex items-center justify-center p-8"><p className="max-w-sm text-center text-[12px] text-zinc-500">{query || lifecycle || source ? 'No matching graph objects. Reset filters to see the full argument.' : 'Add a document or propose a statement in Material to build your argument.'}</p></div>}<div className="absolute bottom-5 left-40 z-5 flex flex-wrap gap-2 max-[700px]:bottom-16 max-[700px]:left-5"><Button size="sm" loading={busy} disabled={!state.graph.statements.length} onClick={() => perform(() => runVerification(state.workspace.id))}>Verify argument</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => { setTab('material'); setSelected(undefined); }}>Add material</Button></div></>
      : tab === 'material' ? <MaterialPanel key={id} state={state} busy={busy} perform={perform} refresh={refresh} onSelect={show}/>
      : tab === 'chain' ? <ArgumentChain state={state} target={target ?? targets[0]?.id ?? state.graph.statements[0]?.id} onSelect={show}/>
      : <ChecksPanel key={id} state={state} busy={busy} lastVerification={lastVerification} perform={perform} refresh={refresh} onVerify={() => runVerification(state.workspace.id)} onSelect={show} onNotice={setNotice}/>}
      {selected && <ResearchInspector key={selected} state={state} id={selected} busy={busy} perform={perform} refresh={refresh} onClose={() => setSelected(undefined)} onSelect={show}/>}</>}
    </div>
    {(error || workspaces.error || current.error && state) && <div role="alert" className="flex shrink-0 items-center justify-between gap-3 border-t border-red-200 bg-red-50 px-5 py-3 text-[11px] text-fail"><span className="break-words">{error || workspaces.error?.message || current.error?.message}</span><Button size="xs" variant="ghost" onClick={() => { setError(''); void refresh(); }}>Retry / dismiss</Button></div>}
    {notice && <div role="status" className="flex shrink-0 items-center justify-between gap-3 border-t border-line bg-white px-5 py-3 text-[11px]"><span>{notice}</span><Button size="xs" variant="ghost" onClick={() => setNotice('')}>Dismiss</Button></div>}
    <footer className="flex min-h-[29px] shrink-0 flex-wrap items-center justify-between gap-2 border-t border-line bg-zinc-50 px-5 py-1 text-[10px] text-zinc-400"><span>{state ? `${state.graph.statements.length} statements · ${state.graph.reasoning_steps.length} reasoning steps · ${state.graph.relations.length} relations` : 'Source excerpts → reviewed argument → proof obligations'}</span><span className="max-[700px]:hidden">Review state and verifier findings · no truth score</span></footer>
  </section></main>;
}
function ChecksPanel({ state, busy, lastVerification, perform, refresh, onVerify, onSelect, onNotice }: { state: Snapshot; busy: boolean; lastVerification?: Verification; perform: (action: () => Promise<void>) => Promise<void>; refresh: () => Promise<void>; onVerify: () => Promise<void>; onSelect: (id: string) => void; onNotice: (message: string) => void }) {
  const [critic, setCritic] = useState<{ event_id: string; checked_steps: number; flagged_steps: number }>();
  const [synthesis, setSynthesis] = useState<{ event_id: string; proposed_links: number; audited_links: number; links_needing_review: number; candidates_considered: number }>();
  return <div className={panel}><h1 className="text-lg">Argument checks</h1><p className="mt-2 max-w-xl text-[11px] leading-relaxed text-zinc-500">Verification identifies unmet requirements. Review and findings concern this argument; they do not prove or disprove a scientific claim.</p>
    <section className={panelSection}><h2>Deterministic verification</h2><Button size="sm" loading={busy} disabled={!state.graph.statements.length} onClick={() => perform(onVerify)}>Run verification</Button>{lastVerification && <div className="mt-4 text-[11px]"><p>{lastVerification.issues_opened} issues opened · {lastVerification.issues_resolved} resolved</p><p>{lastVerification.obligations_opened} obligations opened · {lastVerification.obligations_resolved} resolved</p><p className="mt-2 text-[10px] text-zinc-500">Rules run: {lastVerification.rules_run.map(humanize).join(', ')}</p><p className="mt-2 text-[10px] break-all text-zinc-500">Verification event {lastVerification.verification_event_id}</p></div>}<p className="mt-3 text-[10px] text-zinc-500">Counts include statement and reasoning-step findings. The current API returns detailed findings for statements only. The result above is the last run requested from Checks or Verify argument in this session.</p>{allObligations(state).map(o => <Button key={o.id} size="sm" variant="ghost" className="mt-3 h-auto! w-full justify-between! border-b border-line py-3! text-left whitespace-normal!" onClick={() => onSelect(o.id)}><span>{o.description}</span><span className="ml-3 text-[10px] text-zinc-500">{o.status}</span></Button>)}</section>
    <section className={panelSection}><h2>Evidence-only argument critic</h2><p className="mb-3 text-[11px] leading-relaxed text-zinc-500">Claude checks whether the premise excerpts establish each conclusion without an unstated bridge. Requires the backend’s Claude credentials.</p><Button size="sm" variant="outline" loading={busy} disabled={!state.graph.reasoning_steps.length} onClick={() => perform(async () => { const result = await api.checkArguments(state.workspace.id); setCritic(result); await onVerify(); onNotice(`Critic checked ${result.checked_steps} steps and flagged ${result.flagged_steps}. Verification has been refreshed.`); })}>Check reasoning with Claude</Button>{critic && <p className="mt-3 text-[11px]">{critic.checked_steps} steps checked · {critic.flagged_steps} flagged · Event {critic.event_id}</p>}</section>
    <section className={panelSection}><h2>Cross-source synthesis</h2><p className="mb-3 text-[11px] leading-relaxed text-zinc-500">Propose and audit supports, rebuts and qualifies links across source documents. Generated links remain proposed. Needs-review links are warnings.</p><Button size="sm" variant="outline" loading={busy} disabled={!state.graph.statements.length} onClick={() => perform(async () => { const result = await api.synthesize(state.workspace.id); setSynthesis(result); await refresh(); onNotice(`${result.proposed_links} cross-source links proposed; ${result.links_needing_review} need review.`); })}>Synthesize sources with Claude</Button>{synthesis && <div className="mt-3 text-[11px]"><p>{synthesis.candidates_considered} candidates · {synthesis.proposed_links} proposed links · {synthesis.audited_links} audited · {synthesis.links_needing_review} need review</p><p className="mt-2 text-[10px] break-all">Event {synthesis.event_id}</p></div>}{state.graph.relations.map(r => <Button key={r.id} variant="ghost" size="sm" className="mt-3 h-auto! w-full justify-start! text-left whitespace-normal!" onClick={() => onSelect(r.id)}>{humanize(r.relation)} · {String(r.metadata.audit_verdict ?? 'Proposed relation')} · Inspect link</Button>)}</section>
  </div>;
}
