import { useState } from 'react';
import { Button, Input } from '@cloudflare/kumo';
import type { AssertionMode, PatchOperation, Snapshot, StatementRole } from '../../types/api';
import * as api from '../../lib/research/api';
import { humanize, allObligations } from '../../lib/research/graph';
import { panel, panelSection } from '../ui/classes';
export type Perform = (action: () => Promise<void>) => Promise<void>;
export function MaterialPanel({ state, busy, perform, refresh, onSelect }: { state: Snapshot; busy: boolean; perform: Perform; refresh: () => Promise<void>; onSelect: (id: string) => void }) {
  const [files, setFiles] = useState<File[]>([]); const [automatic, setAutomatic] = useState(false); const [fileKey, setFileKey] = useState(0);
  const [sourceId, setSourceId] = useState(''); const [jobId, setJobId] = useState('');
  const [text, setText] = useState(''); const [mode, setMode] = useState<AssertionMode>('asserted'); const [role, setRole] = useState<StatementRole>('premise'); const [excerptIds, setExcerptIds] = useState<string[]>([]);
  const [conclusion, setConclusion] = useState(''); const [premises, setPremises] = useState<string[]>([]); const [explanation, setExplanation] = useState(''); const [patchText, setPatchText] = useState('');
  const [relationSource, setRelationSource] = useState(''); const [relationTarget, setRelationTarget] = useState(''); const [relationKind, setRelationKind] = useState<'supports' | 'rebuts' | 'undercuts' | 'qualifies' | 'specializes' | 'revises'>('supports'); const [relationReason, setRelationReason] = useState('');
  const objects = [...state.graph.statements.map(s => ({ id: s.id, label: s.text, kind: 'statement' as const })), ...state.graph.reasoning_steps.map(s => ({ id: s.id, label: s.explanation, kind: 'reasoning_step' as const }))];
  const id = state.workspace.id;
  async function patch(operations: PatchOperation[]) { await api.patchGraph(id, operations); await refresh(); }
  return <div className={panel}><h1 className="text-lg tracking-tight">Research material</h1><p className="mt-2 max-w-xl text-[11px] leading-relaxed text-zinc-500">Exact excerpts anchor proposed statements. Review statements and reasoning before relying on the argument.</p>
    <section className={panelSection}><h2>Add documents</h2><input key={fileKey} aria-label="Research documents" type="file" accept=".md,.markdown,.txt,text/plain,text/markdown" multiple onChange={e => setFiles(Array.from(e.target.files ?? []))} className="my-3 block max-w-full text-[11px]"/>
      <label className="mb-3 flex items-center gap-2 text-[11px]"><input type="checkbox" checked={automatic} onChange={e => setAutomatic(e.target.checked)}/>Queue Claude extraction after upload</label>
      <Button size="sm" loading={busy} disabled={!files.length} onClick={() => perform(async () => {
        for (const file of files) {
          if (!/\.(txt|md|markdown)$/i.test(file.name)) throw new Error('Choose UTF-8 .txt, .md or .markdown files.');
          if (file.size > 10 * 1024 * 1024) throw new Error(`${file.name} exceeds the 10 MB upload limit.`);
          const source = await api.uploadSource(id, file); if (automatic) await api.extract(source);
        }
        setFiles([]); setFileKey(k => k + 1); await refresh();
      })}>{automatic ? 'Upload and extract' : 'Upload documents'}</Button><p className="mt-2 text-[10px] text-zinc-500">UTF-8 text and Markdown · 10 MB per document. Manual graph editing works without model credentials.</p>
      {state.jobs.map(j => <div key={j.id} className="mt-3 border-t border-line pt-3 text-[11px]"><strong>{state.sources.find(s => s.id === j.source_id)?.original_filename ?? j.source_id}</strong><p className="mt-1">{humanize(j.status)} · {j.completed_chunks}/{j.total_chunks} chunks · {j.attempts} attempts</p><p className="mt-1 text-[10px] text-zinc-500">{j.model} · Job {j.id}</p>{j.error && <p className="mt-2 text-fail" role="alert">{j.error}</p>}{!['succeeded', 'failed', 'cancelled'].includes(j.status) && <Button size="xs" variant="ghost" disabled={busy} onClick={() => perform(async () => { await api.cancelJob(j.id); await refresh(); })}>Cancel extraction</Button>}{['failed', 'cancelled'].includes(j.status) && <Button size="xs" variant="outline" disabled={busy} onClick={() => perform(async () => { const source = state.sources.find(s => s.id === j.source_id) ?? await api.attachSource(id, j.source_id); await api.extract(source); await refresh(); })}>Retry extraction</Button>}</div>)}
    </section>
    <section className={panelSection}><h2>Source ledger</h2>{state.sources.map(s => <div key={s.id} className="mb-5 border-b border-line pb-4"><div className="flex flex-wrap items-center gap-3"><Button size="sm" variant="ghost" className="h-auto! text-left whitespace-normal!" onClick={() => onSelect(s.id)}>{s.original_filename}</Button><Button size="xs" variant="outline" disabled={busy} onClick={() => perform(async () => { await api.extract(s); await refresh(); })}>Extract argument</Button></div><p className="mt-2 text-[10px] text-zinc-500">{s.excerpts.length} immutable excerpts · Source {s.id}</p>{s.excerpts.map(e => <Button key={e.id} size="xs" variant="ghost" className="mt-2 h-auto! w-full justify-start! text-left whitespace-normal!" onClick={() => onSelect(e.id)}>{e.text}</Button>)}</div>)}{!state.sources.length && <p className="text-[11px] text-zinc-500">Upload a document to start a source ledger.</p>}
      <details className="mt-4"><summary className="cursor-pointer text-[11px]">Reconnect a source or extraction job</summary><p className="my-3 text-[10px] text-zinc-500">Source and job IDs are remembered in this browser. Use an ID from another session or an exported snapshot to reconnect existing material.</p><div className="flex gap-2"><Input size="sm" aria-label="Existing source ID" placeholder="Source UUID" value={sourceId} onChange={e => setSourceId(e.target.value)}/><Button size="sm" disabled={busy || !sourceId.trim()} onClick={() => perform(async () => { await api.attachSource(id, sourceId.trim()); setSourceId(''); await refresh(); })}>Attach source</Button></div><div className="mt-3 flex gap-2"><Input size="sm" aria-label="Existing job ID" placeholder="Job UUID" value={jobId} onChange={e => setJobId(e.target.value)}/><Button size="sm" disabled={busy || !jobId.trim()} onClick={() => perform(async () => { const job = await api.attachJob(id, jobId.trim()); await api.attachSource(id, job.source_id); setJobId(''); await refresh(); })}>Attach job</Button></div></details>
    </section>
    <section className={panelSection}><h2>Propose a statement</h2><div className="grid gap-3"><Input size="sm" label="Statement text" value={text} onChange={e => setText(e.target.value)}/><div className="flex flex-wrap gap-4"><label>Assertion <select aria-label="Assertion mode" className="rounded border border-line p-2" value={mode} onChange={e => setMode(e.target.value as AssertionMode)}>{['asserted', 'hypothesis', 'conditional', 'question', 'reported'].map(m => <option key={m}>{m}</option>)}</select></label><label>Role <select aria-label="Statement role" className="rounded border border-line p-2" value={role} onChange={e => setRole(e.target.value as StatementRole)}>{['premise', 'conclusion', 'assumption', 'objection', 'definition'].map(m => <option key={m}>{m}</option>)}</select></label></div><p className="text-[10px] text-zinc-500">Select the excerpts that ground this statement.</p>{state.sources.flatMap(s => s.excerpts).map(e => <label key={e.id} className="flex items-start gap-2 text-[11px]"><input type="checkbox" checked={excerptIds.includes(e.id)} onChange={ev => setExcerptIds(ev.target.checked ? [...excerptIds, e.id] : excerptIds.filter(x => x !== e.id))}/>{e.text}</label>)}<Button size="sm" disabled={busy || !text.trim()} className="justify-self-start" onClick={() => perform(async () => { await patch([{ op: 'create_statement', client_ref: 'statement', text: text.trim(), assertion_mode: mode, role, excerpt_ids: excerptIds, provenance: api.userProvenance }]); setText(''); setExcerptIds([]); })}>Propose statement</Button></div></section>
    <section className={panelSection}><h2>Declare a reasoning step</h2><p className="mb-3 text-[10px] text-zinc-500">All selected premises are required together. Separate steps represent alternative support paths.</p><label>Conclusion<select aria-label="Reasoning conclusion" className="mt-1 w-full rounded border border-line p-2" value={conclusion} onChange={e => { setConclusion(e.target.value); setPremises(p => p.filter(x => x !== e.target.value)); }}><option value="">Choose a conclusion</option>{state.graph.statements.map(s => <option key={s.id} value={s.id}>{s.text}</option>)}</select></label><div className="my-3 grid gap-2">{state.graph.statements.filter(s => s.id !== conclusion).map(s => <label key={s.id} className="flex items-start gap-2 text-[11px]"><input type="checkbox" checked={premises.includes(s.id)} onChange={e => setPremises(e.target.checked ? [...premises, s.id] : premises.filter(p => p !== s.id))}/>{s.text}</label>)}</div><Input size="sm" label="Reasoning explanation" value={explanation} onChange={e => setExplanation(e.target.value)}/><Button size="sm" className="mt-3" disabled={busy || !conclusion || !premises.length || !explanation.trim()} onClick={() => perform(async () => { await patch([{ op: 'create_reasoning_step', client_ref: 'reasoning', premise_ids: premises, conclusion_id: conclusion, explanation: explanation.trim(), provenance: api.userProvenance }]); setExplanation(''); setPremises([]); setConclusion(''); })}>Propose reasoning step</Button></section>
    <section className={panelSection}><h2>Propose a relation</h2><p className="mb-3 text-[10px] text-zinc-500">Link argument objects with an explicit rationale. Relations remain inspectable proposals.</p><div className="grid gap-3"><label>From<select aria-label="Relation source" className="mt-1 w-full rounded border border-line p-2" value={relationSource} onChange={e => setRelationSource(e.target.value)}><option value="">Choose an argument object</option>{objects.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label>Relation<select aria-label="Relation kind" className="ml-3 rounded border border-line p-2" value={relationKind} onChange={e => setRelationKind(e.target.value as typeof relationKind)}>{['supports', 'rebuts', 'undercuts', 'qualifies', 'specializes', 'revises'].map(r => <option key={r}>{r}</option>)}</select></label><label>To<select aria-label="Relation target" className="mt-1 w-full rounded border border-line p-2" value={relationTarget} onChange={e => setRelationTarget(e.target.value)}><option value="">Choose an argument object</option>{objects.filter(o => o.id !== relationSource).map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label><Input size="sm" label="Relation rationale" value={relationReason} onChange={e => setRelationReason(e.target.value)}/><Button size="sm" className="justify-self-start" disabled={busy || !relationSource || !relationTarget || relationSource === relationTarget || !relationReason.trim()} onClick={() => perform(async () => { const from = objects.find(o => o.id === relationSource)!; const to = objects.find(o => o.id === relationTarget)!; await patch([{ op: 'create_relation', source_node_kind: from.kind, source_node_id: from.id, target_node_kind: to.kind, target_node_id: to.id, relation: relationKind, metadata: { lifecycle: 'proposed', rationale: relationReason.trim(), provenance: api.userProvenance } }]); setRelationReason(''); setRelationSource(''); setRelationTarget(''); })}>Propose relation</Button></div></section>
    <section className={panelSection}><h2>Review candidates</h2>{state.graph.statements.map(s => <Button variant="ghost" size="sm" key={s.id} className="h-auto! w-full justify-between! border-b border-line py-3! text-left text-[11px]! whitespace-normal!" onClick={() => onSelect(s.id)}><span>{s.text}</span><span className="ml-4 shrink-0 text-[10px] text-zinc-500">{s.lifecycle}</span></Button>)}</section>
    <details className={panelSection}><summary className="cursor-pointer text-[11px]">Advanced graph patch</summary><p className="my-2 text-[10px] text-zinc-500">Backend operations: create_statement, create_reasoning_step, create_relation, create_annotation. Every statement and reasoning step remains proposed until reviewed. References and workspace boundaries are validated by the API.</p><textarea aria-label="Graph patch operations" className="min-h-40 w-full rounded border border-line p-3 font-mono text-[11px]" value={patchText} onChange={e => setPatchText(e.target.value)}/><Button size="sm" className="mt-2" disabled={busy || !patchText.trim()} onClick={() => perform(async () => { const ops: unknown = JSON.parse(patchText); if (!Array.isArray(ops) || !ops.length) throw new Error('Enter a non-empty JSON operations array.'); await patch(ops as PatchOperation[]); setPatchText(''); })}>Submit graph patch</Button></details>
  </div>;
}
export function ArgumentChain({ state, target, onSelect }: { state: Snapshot; target?: string; onSelect: (id: string) => void }) {
  function render(id: string, path = new Set<string>(), depth = 0): React.ReactNode {
    if (path.has(id) || depth > 20) return <p className="text-warn">Dependency limit reached.</p>;
    const next = new Set([...path, id]); const steps = state.graph.reasoning_steps.filter(r => r.conclusion_id === id);
    return <div key={id} className="mt-3 border-l border-line pl-4"><Button variant="ghost" size="sm" className="h-auto! justify-start! px-0! text-left whitespace-normal!" onClick={() => onSelect(id)}>{state.graph.statements.find(s => s.id === id)?.text}</Button>{allObligations(state).filter(o => o.status === 'open' && o.blocks_statement_id === id).map(o => <Button key={o.id} variant="ghost" size="xs" className="mt-2 h-auto! text-left text-fail! whitespace-normal!" onClick={() => onSelect(o.id)}>{o.description}</Button>)}{steps.map(r => <div key={r.id} className="my-3 rounded border border-line p-3"><Button variant="ghost" size="xs" className="h-auto! text-left whitespace-normal!" onClick={() => onSelect(r.id)}>{r.explanation} · {r.lifecycle}</Button><p className="mt-2 text-[10px] text-zinc-500">All premises below are required together{steps.length > 1 ? ' · alternative support step' : ''}</p>{r.premise_ids.map(p => render(p, next, depth + 1))}</div>)}</div>;
  }
  return <div className={panel}><h1 className="text-lg">Argument chain</h1><p className="mt-2 text-[11px] text-zinc-500">Reasoning steps retain their premise groups. Inspect every dependency before accepting a conclusion.</p>{target ? render(target) : <p className="mt-6 text-zinc-500">Choose a statement on the argument canvas.</p>}</div>;
}
